

export const ADD_INGREDIENT = 'ADD_INGREDIENT';

export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';

export const SET_INIT_INGREDIENTS = 'SET_INIT_INGREDIENTS';

export const SET_INIT_INGREDIENTS_FAIL = 'SET_INIT_INGREDIENTS_FAIL';



export const FETCH_ORDERS_SUCCESS = 'SET_FETCH_ORDERS'

export const FETCH_ORDERS_START_ALERT = 'FETCH_ORDERS_START_ALERT';

export const FETCH_ORDERS_FAIL = 'FETCH_ORDERS_FAIL';



export const PLACE_ORDER = 'PLACE_ORDER';

export const PLACE_ORDER_START_ALERT = 'PLACE_ORDER_START_ALERT';

export const PLACE_ORDER_FAIL = 'PLACE_ORDER_FAIL';

export const PURCHASE_INIT = 'PURCHASE_INIT'



export const AUTH_START_ALERT = 'AUTH_START_ALERT'

export const AUTH_SUCCESS = 'AUTH_SUCCESS'

export const AUTH_FAIL = 'AUTH_FAIL'

export const AUTH_LOGOUT ='AUTH_LOGOUT'

export const SET_AUTH_REDIRECT_PATH ='SET_AUTH_REDIRECT_PATH'

